config/routes.rb
Rails.application.routes.draw do
  # Users routes
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "welcome#index"

  namespace :admin do
    resources :mosques, only: [ :index ]
  end

  resources :mosques do
    resources :salah_timings
    collection do
      get "search"
      get "suggest", controller: "welcome", action: :suggest
      post "suggest", controller: "welcome", action: :create
    end
  end

  post "/telegram_webhook", to: "telegram#webhook"
  get "/telegram_login", to: "telegram_web#login"
  # namespace :telegram_api do
  #   post "/bot/login", to: "bot#login"
  #   post "/auth/web_login", to: "auth#new"
  # end
end

app/views/shared/_footer.html.erb
<footer class="mt-auto text-white-50">
  <p>Tooba Masjid &copy <%=DateTime.now.year%></p>
</footer>

app/views/shared/_header.html.erb
<header class="mb-auto">
    <div>
        <h3 class="float-md-start mb-2">Namaz Time</h3>
        <nav class="nav nav-masthead justify-content-center float-md-end d-flex">
            <a class="nav-link fw-bold py-1 px-0 active" aria-current="page" href="/">Home &emsp;</a> 
            <a class="nav-link fw-bold py-1 px-0" href="#">Contact &emsp;</a>
            <% if user_signed_in? %>
                <% if current_user.admin? %>
                    <%= link_to "Dashboard", admin_mosques_path, class: "nav-link fw-bold py-1 px-0" %>
                <% elsif current_user.muazzin? %>
                    <%= link_to "Mosques", mosques_path, class: "nav-link fw-bold py-1 px-0" %>                    
                <% end %>
                <%= link_to current_user.full_name, edit_user_registration_path, class: "nav-link fw-bold py-1 px-0" %>
                <%= link_to "Log out", destroy_user_session_path, data: { "turbo-method": :delete }, class: "nav-link fw-bold py-1 px-0" %>
            <% else %>
                <%= link_to "Log in", new_user_session_path, class: "nav-link fw-bold py-1 px-0" %>
                <%= link_to "Register", new_user_registration_path, class: "nav-link fw-bold py-1 px-0" %>
            <% end %>
        </nav>
    </div>
</header>