config/routes.rb
Rails.application.routes.draw do
  # Users routes
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "welcome#index"

  namespace :admin do
    resources :mosques, only: [ :index ]
  end

  resources :mosques do
    resources :salah_timings
    collection do
      get "search"
      get "suggest", controller: "welcome", action: :suggest
      post "suggest", controller: "welcome", action: :create
    end
  end

  post "/telegram_webhook", to: "telegram#webhook"
  get "/telegram_login", to: "telegram_web#login"
  # namespace :telegram_api do
  #   post "/bot/login", to: "bot#login"
  #   post "/auth/web_login", to: "auth#new"
  # end
end

app/models/mosque.rb
class Mosque < ApplicationRecord
  belongs_to :area
  has_many :salah_timings, dependent: :destroy
  belongs_to :user

  validates :name, :address, :user_id, presence: true

  APPROVED = "approved".freeze
  PENDING = "pending".freeze
  enum :status, approved: APPROVED, pending: PENDING, default: :pending

  def next_salah_time
    current_time = Time.now.utc.strftime("%H:%M")
    if current_time > salah_timings.last.timing.strftime("%H:%M")
      salah_timings.first
    else
      salah_timings.find { |st| st.timing.strftime("%H:%M") > current_time }
    end
  end
end

app/controllers/admin/mosques_controller.rb
module Admin
  class MosquesController < ApplicationController
    before_action :authenticate_user!
    authorize_resource

    layout "admin"

    def index
      @mosques = Mosque.all
      @type = "all"
      if params[:status] == "pending"
        @mosques = Mosque.pending
        @type = "pending"
      elsif params[:status] == "approved"
        @mosques = Mosque.approved
        @type = "approved"
      end
    end
  end
end

app/controllers/mosques_controller.rb
class MosquesController < ApplicationController
  before_action :authenticate_user!, except: [ :search, :show ]
  before_action :set_mosque, only: [ :edit, :update, :show, :destroy ]

  def index
    @mosques = Mosque.includes(:area, :user).where(user_id: current_user.id)
  end

  def new
    @mosque = Mosque.new
  end

  def create
    @mosque = Mosque.new(mosque_params)
    @mosque.user_id = current_user.id # logged-in user
    @mosque.status = Mosque::APPROVED
    if @mosque.save
      redirect_to mosques_path, notice: "Masjid added successfully."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @mosque.update(mosque_params)
      redirect_to mosques_path, notice: "Masjid updated successfully."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @mosque.destroy
    redirect_to mosques_path, notice: "Masjid details deleted."
  end


  def search
    @mosques = Mosque.where(area_id: params[:query])
  end

  def show; end

  private

  def set_mosque
    @mosque = Mosque.find(params[:id])
  end

  def mosque_params
    params.require(:mosque).permit(:name, :address, :area_id, :user_id, :google_link)
  end
end

app/views/mosques/_form.html.erb
<% if @mosque.new_record? %>
  <h1>Add new masjid</h1>
<% else %>
  <h1>Edit masjid</h1>
<% end %><br>

<%= form_with(model: @mosque, local: true) do |form| %>
  <div class="mb-3">
    <%= form.label :name, "Name of MASJID", class: "form-label fw-bold fst-italic" %>
    <%= form.text_field :name, class: "form-control" %> 
  </div>
  
  <br>

  <div class="mb-3">
    <%= form.label :address, "Address", class: "form-label fw-bold fst-italic" %>
    <%= form.text_area :address, class: "form-control" %>
  </div>
  
  <br>
    
  <div class="mb-3">
    <%= form.label :area, "Area", class: "form-label fw-bold fst-italic" %>
    <%= form.select :area_id, options_for_select(Area.all.map {|a| [a.area_name, a.id]}, @mosque.area_id), {prompt: "Select Area"},class:"form-select" %>
 </div>
 
 <br>

  <div class="field">
    <%= form.label :google_link, "Google link", class: "form-label fw-bold fst-italic" %>
    <%= form.text_area :google_link, class: "form-control" %>
  </div>
  
  <br>

  <%= form.submit nil,class: "btn btn-primary fw-bold fst-italic" %>
  
<% end %>

app/views/mosques/edit.html.erb
<%= render 'form' %>

app/views/mosques/index.html.erb
<h1>List of Masjids</h1>
<table class="table table-light table-bordered" >
  <thead>
    <tr>
      <th scope="col">Sr.no</th>
      <th scope="col">Mosque Name</th>
      <th scope="col">Mosque Adress</th> 
      <th scope="col">Area</th>
      <th scope="col">User</th>
      <th scope="col">Details</th>
      <th scope="col">Manage</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    <%= link_to "ADD NEW Masjid", new_mosque_path %> <br/>
    <%@mosques.each_with_index do |mosque, index|%>
        <tr>
            <td><%=index+1%></td>
            <td><%=mosque.name%></td>
            <td><%=mosque.address%></td>
            <td><%=mosque.area.area_name%></td>
            <td><%=mosque.user.full_name%></td>
            <td><%= link_to "Salah Timings", mosque_path(mosque.id)  %></td>
            <td><%= link_to  "Edit", edit_mosque_path(mosque.id)%></td>
            <td><%= link_to "DELETE", mosque_path(mosque.id),data:{turbo_method: :delete,turbo_confirm: "Are you sure?"} %> </td>
        </tr>
    <%end%>
  </tbody>
</table>

app/views/mosques/new.html.erb
<%= render 'form' %>

app/views/mosques/search.html.erb
<h1>Search Masjids</h1>
<%= form_with url: "/mosques/search", method: :get do |form| %>
  <%= form.label :query, "Search for:" %>
  <%= form.select :query, options_for_select(Area.all.map {|a| [a.area_name, a.id]}, params[:query]), {prompt: "Select Area"},class:"form-select" %>
  <%= form.submit "Search" %>
<% end %>


<table class="table table-light table-bordered" >
  <thead>
    <tr>
      <th scope="col">Sr.no</th>
      <th scope="col">Mosque Name</th>
      <th scope="col">Mosque Adress</th>
      <th scope="col">Google Link</th>
      <th scope="col">Upcoming Namaaz</th>
    </tr>
  </thead>
  <tbody>
    <%= link_to "New", new_mosque_path %>
    <%@mosques.each_with_index do |mosque, index|%>
        <tr>
            <td><%=index+1%></td>
            <td><%=mosque.name%></td>
            <td><%=mosque.address%></td>
            <td><a href = "<%=mosque.google_link%>">Google Link</a></td>
            <td><%= local_time(mosque.next_salah_time.timing, "%I:%M %P")%>
            - <b><%=mosque.next_salah_time.name%><b>
            </td>
        </tr>
    <%end%>
  </tbody>
</table>

app/views/mosques/show.html.erb
<h1>Namaz Timings of <%=@mosque.name%> </h1> 
 <%= link_to "Add NEW SALAH", "/mosques/#{@mosque.id}/salah_timings/new" %><br/>
<table class="table table-light table-bordered" >
  <thead>
    <tr>      
      <th scope="col"> Namaz </th>
      <th scope="col"> Timings </th>
      <th scope="col"> Action </th>
    </tr>
  </thead>
  <tbody>
    <% @mosque.salah_timings.each do |t| %>
      <tr>
        <td> <%= t.name %> </td>
        <td> <%= t.timing.strftime("%I:%M %P") %> </td>
        <td> <%= link_to "EDIT",edit_mosque_salah_timing_path(@mosque.id, t.id) %> </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Back', :back %>